name: Primary
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }} @ ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  primary-sleep:
    name: primary-sleep-name
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        instance: [30, 60, 90, 120]
    steps:
      - name: Echo Primary Instance
        run: echo "Instance ${{ matrix.instance }}"
      - name: Do Primary Sleep
        run: |
          echo "Sleeping for 30s"
          sleep ${{ matrix.instance }}
          echo "Done."
