name: Workflow One
on:
  push

concurrency:
  group: ${{github.workflow}}-${{ (contains(fromJson('["main", "master"]'), github.ref) && github.run_id) || github.ref }}
  cancel-in-progress: true
# This cancelled the workflow on main
#  group: check-${{ github.ref }}

jobs:
  sleep:
      name: sleep
      strategy:
        max-parallel: 2
        matrix:
          os: [ubuntu-22.04, ubuntu-20.04]
      runs-on: ${{ matrix.os }}
      steps:
        - name: Echo Name
          run: echo "${{github.workflow}}-${{ (contains(fromJson('["main", "master"]'), github.ref) && github.run_id) || github.ref }}"
        - name: Echo Parts
          run: |
            echo "Workflow: ${{ github.workflow }}"
            echo "Branches: ${{ contains(fromJson('["main", "master"]'), github.ref) }}"
            echo "Run ID:   ${{ github.run_id }}"
            echo "Ref:      ${{ github.ref }}"
        - name: Sleep
          run: |
            echo "Sleeping for 3m"
            sleep 180
            echo "Done."