name: check
on:
  push

concurrency:
  cancel-in-progress: true
  group: check-${{ github.head_ref || github.run_id }}
# This cancelled the workflow on main
#  group: check-${{ github.ref }}

jobs:
  sleep:
      name: sleep
      runs-on: ubuntu-20.04
      steps:
        - name: Sleep
          run: |
            echo "Sleeping for 5m"
            sleep 300
            echo "Done."