name: Workflow Two
on:
  push

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
# This cancelled the workflow on main
#  group: check-${{ github.ref }}

jobs:
  sleep:
      name: sleep
      strategy:
        max-parallel: 2
        matrix:
          os: [ubuntu-22.04, ubuntu-20.04]
      runs-on: ${{ matrix.os }}
      steps:
        - name: Sleep
          run: |
            echo "Sleeping for 5m"
            sleep 300
            echo "Done."