name: Workflow One
on:
  push

concurrency:
  group: ${{ github.workflow }} @ ${{ github.event_name == 'pull_request' && github.ref || github.run_id }})
  cancel-in-progress: true

jobs:
  sleep:
      name: sleep
      strategy:
        max-parallel: 2
        matrix:
          os: [ubuntu-22.04, ubuntu-20.04]
      runs-on: ${{ matrix.os }}
      steps:
        - name: Echo Name
          run: echo "${{ github.workflow }} @ ${{ github.event_name == 'pull_request' && github.ref || github.run_id }})"
        - name: Echo Parts
          run: |
            echo "Workflow: ${{ github.workflow }}"
            echo "Branches: ${{ contains(github.ref, github.event.repository.default_branch) }}"
            echo "Run ID:   ${{ github.run_id }}"
            echo "Ref:      ${{ github.ref }}"
        - name: Sleep
          run: |
            echo "Sleeping for 3m"
            sleep 180
            echo "Done."